-- MySQL Script generated by MySQL Workbench
-- mié 01 may 2024 22:08:35
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`cliente` (
  `id_cliente` INT NOT NULL AUTO_INCREMENT,
  `cedula` VARCHAR(50) NOT NULL,
  `nombre` VARCHAR(50) NULL,
  `correo` VARCHAR(100) NOT NULL,
  `contrasena` VARCHAR(80) NOT NULL,
  `telefono` VARCHAR(50) NULL,
  PRIMARY KEY (`id_cliente`),
  UNIQUE INDEX `cedula_UNIQUE` (`cedula` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`producto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`producto` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(50) NULL,
  `modelo` VARCHAR(100) NULL,
  `descripcion` VARCHAR(200) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`ticket`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`ticket` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `id_producto` INT NOT NULL,
  `id_cliente` INT NOT NULL,
  `fecha_creacion` DATE NULL,
  `fecha_cierre` DATE NULL,
  `descripcion` VARCHAR(100) NULL,
  `asunto` VARCHAR(100) NULL,
  `status` ENUM('ABIERTO', 'ESPERANDO', 'CERRADO', 'CANCELADO') NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_cliente_idx` (`id_cliente` ASC) VISIBLE,
  INDEX `fk_producto_idx` (`id_producto` ASC) VISIBLE,
  CONSTRAINT `fk_cliente`
    FOREIGN KEY (`id_cliente`)
    REFERENCES `mydb`.`cliente` (`id_cliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_producto`
    FOREIGN KEY (`id_producto`)
    REFERENCES `mydb`.`producto` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`factura`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`factura` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `id_cliente` INT NOT NULL,
  `fecha_emision` DATETIME NULL,
  `total` FLOAT NULL,
  `status` ENUM('PAGADA', 'CANCELADA', 'EN ESPERA') NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_cliente_idx` (`id_cliente` ASC) VISIBLE,
  CONSTRAINT `fk_cliente_id`
    FOREIGN KEY (`id_cliente`)
    REFERENCES `mydb`.`cliente` (`id_cliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`empleado`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`empleado` (
  `id_empleado` INT NOT NULL AUTO_INCREMENT,
  `cedula` VARCHAR(50) NOT NULL,
  `nombre` VARCHAR(50) NULL,
  `rol` VARCHAR(50) NULL,
  `telefono` VARCHAR(50) NULL,
  `correo` VARCHAR(45) NOT NULL,
  `contrasena` VARCHAR(80) NOT NULL,
  PRIMARY KEY (`id_empleado`),
  UNIQUE INDEX `cedula_UNIQUE` (`cedula` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`responsable_ticket`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`responsable_ticket` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `id_ticket` INT NOT NULL,
  `id_empleado` INT NOT NULL,
  `fecha_asignacion` DATE NULL,
  `comentario` VARCHAR(100) NULL,
  `status` ENUM('ABIERTO', 'ESPERANDO', 'CERRADO', 'CANCELADO') NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_ticket_idx` (`id_ticket` ASC) VISIBLE,
  INDEX `fk_empleado_idx` (`id_empleado` ASC) VISIBLE,
  CONSTRAINT `fk_ticket`
    FOREIGN KEY (`id_ticket`)
    REFERENCES `mydb`.`ticket` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_empleado`
    FOREIGN KEY (`id_empleado`)
    REFERENCES `mydb`.`empleado` (`id_empleado`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`historial_ticket`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`historial_ticket` (
  `id_historial` INT NOT NULL AUTO_INCREMENT,
  `id_ticket` INT NOT NULL,
  `id_responsable` INT NOT NULL,
  `fecha_seguimiento` DATETIME NULL,
  `respuesta` VARCHAR(100) NULL,
  `is_client` TINYINT NULL,
  PRIMARY KEY (`id_historial`),
  INDEX `fk_responsable_idx` (`id_responsable` ASC) VISIBLE,
  INDEX `fk_ticket_idx` (`id_ticket` ASC) VISIBLE,
  CONSTRAINT `fk_responsable`
    FOREIGN KEY (`id_responsable`)
    REFERENCES `mydb`.`responsable_ticket` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ticket_id`
    FOREIGN KEY (`id_ticket`)
    REFERENCES `mydb`.`ticket` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`garantia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`garantia` (
  `id_garantia` INT NOT NULL AUTO_INCREMENT,
  `id_producto` INT NOT NULL,
  `descripcion` VARCHAR(100) NULL,
  `duracion` DATETIME NULL,
  PRIMARY KEY (`id_garantia`),
  INDEX `fk_producto_idx` (`id_producto` ASC) VISIBLE,
  CONSTRAINT `fk_g_producto`
    FOREIGN KEY (`id_producto`)
    REFERENCES `mydb`.`producto` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`detalle_factura`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`detalle_factura` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `id_factura` INT NOT NULL,
  `id_producto` INT NOT NULL,
  `cantidad` INT NULL,
  `precio_unitario` FLOAT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_factura_idx` (`id_factura` ASC) VISIBLE,
  INDEX `fk_producto_idx` (`id_producto` ASC) VISIBLE,
  CONSTRAINT `fk_df_factura`
    FOREIGN KEY (`id_factura`)
    REFERENCES `mydb`.`factura` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_df_producto`
    FOREIGN KEY (`id_producto`)
    REFERENCES `mydb`.`producto` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
